//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr5BB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public long ID_equipment { get; set; }
        public string Name { get; set; }
        public decimal price { get; set; }
        public int equipment_code { get; set; }
    
        public virtual Equipment_type Equipment_type { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
