//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr5BB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Geners_Singers
    {
        public long ID_genres_singers { get; set; }
        public long ID_genre { get; set; }
        public long ID_singer { get; set; }
    
        public virtual Geners Geners { get; set; }
        public virtual Singers Singers { get; set; }
    }
}
