//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr5BB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public string ID_sale { get; set; }
        public System.DateTime sale_date { get; set; }
        public int quantity_sold { get; set; }
        public decimal price_per_unit { get; set; }
    
        public virtual Albums Albums { get; set; }
        public virtual Stories Stories { get; set; }
    }
}
